language: rust
rust:
- nightly
branches:
  only:
    - bench
script: ! '[ $TRAVIS_BRANCH = bench ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  export PATH=$HOME/.local/bin:$PATH &&
  cargo bench &&
  python bench_results.py &&
  git config user.email "lukas.schmierer@lschmierer.de" &&
  git config user.name "Lukas Schmierer" &&
  git add README.md &&
  git commit -q -m "update benchmark results" &&
  git push -q -f https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:master
'
