[package]
name = "ecs_bench"
version = "0.1.0"
authors = ["Lukas Schmierer <lukas.schmierer@lschmierer.de>"]

[dev-dependencies]
ecs = "0.23"

[dev-dependencies.parsec]
git = "https://github.com/kvark/parsec"
